// Generated by CoffeeScript 1.7.1
(function() {
  var Mutation, accumuloTypes;

  accumuloTypes = require('./thrift-generated/proxy_types');

  Mutation = (function() {
    function Mutation(row) {
      this.row = row;
      this.updates = [];
    }

    Mutation.prototype.put = function(options) {
      var colup, _ref, _ref1, _ref2, _ref3, _ref4;
      if (options == null) {
        options = {};
      }
      colup = new accumuloTypes.ColumnUpdate();
      colup.colFamily = (_ref = options.columnFamily) != null ? _ref : '';
      colup.colQualifier = (_ref1 = options.columnQualifier) != null ? _ref1 : '';
      colup.colVisibility = (_ref2 = options.columnVisibility) != null ? _ref2 : '';
      colup.timestamp = (_ref3 = options.timestamp) != null ? _ref3 : null;
      colup.value = (_ref4 = options.value) != null ? _ref4 : '';
      return this.updates.push(colup);
    };

    return Mutation;

  })();

  exports.Mutation = Mutation;

}).call(this);
