// Generated by CoffeeScript 1.7.1
(function() {
  var BaseIterator, accumuloTypes;

  accumuloTypes = require('../thrift-generated/proxy_types');

  BaseIterator = (function() {
    function BaseIterator(options) {
      this.options = options;
    }

    BaseIterator.prototype.getIteratorProperties = function() {
      return {};
    };

    BaseIterator.prototype.getIteratorSetting = function() {
      var i;
      i = new accumuloTypes.IteratorSetting();
      i.name = this.options.name;
      i.priority = this.options.priority;
      i.iteratorClass = this.options.classname;
      i.properties = this.getIteratorProperties();
      return i;
    };

    return BaseIterator;

  })();

  exports.BaseIterator = BaseIterator;

}).call(this);
