// Generated by CoffeeScript 1.7.1
(function() {
  var BaseIterator, RegExFilter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseIterator = require('./baseiterator').BaseIterator;

  RegExFilter = (function(_super) {
    __extends(RegExFilter, _super);

    function RegExFilter(options) {
      var _ref, _ref1, _ref2;
      this.options = options != null ? options : {};
      this.options.name = (_ref = this.options.name) != null ? _ref : 'RegExFilter';
      this.options.priority = (_ref1 = this.options.priority) != null ? _ref1 : 10;
      this.options.classname = (_ref2 = this.options.classname) != null ? _ref2 : 'org.apache.accumulo.core.iterators.user.RegExFilter';
    }

    RegExFilter.prototype.getIteratorProperties = function() {
      var props, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      props = {};
      if (props.rowRegex == null) {
        props.rowRegex = (_ref = this.options.rowRegex) != null ? _ref : null;
      }
      if (props.colfRegex == null) {
        props.colfRegex = (_ref1 = this.options.familyRegex) != null ? _ref1 : null;
      }
      if (props.colqRegex == null) {
        props.colqRegex = (_ref2 = this.options.qualifierRegex) != null ? _ref2 : null;
      }
      if (props.valueRegex == null) {
        props.valueRegex = (_ref3 = this.options.valueRegex) != null ? _ref3 : null;
      }
      props.orFields = ((_ref4 = this.options.orFields) != null ? _ref4 : false).toString().toLowerCase();
      props.matchSubstring = ((_ref5 = this.options.matchSubstring) != null ? _ref5 : false).toString().toLowerCase();
      return props;
    };

    return RegExFilter;

  })(BaseIterator);

  exports.RegExFilter = RegExFilter;

}).call(this);
